
package vue;

import controleur.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modele.*;

/**
 * @version Prototype_1
 * @author GUAY Alexis
 * Class ListePorteur correspond à la vue qui affichera tout les porteurs présents dans le bouchon.
 */
public class ListePorteur extends javax.swing.JFrame {

    private final Main link_main;
    private final ArrayList<Porteur> lesPorteurs;
    private final ArrayList<Club> lesClubs;
    /**
     * 
     * @param link_main
     * Création de la vue ListePorteur
     */
    public ListePorteur(Main link_main) {
        initComponents();
        this.link_main = link_main;
        this.lesPorteurs = link_main.getLesPorteurs();
        this.lesClubs = link_main.getLesClubs();
        
        
             
       DefaultTableModel tm1 = (DefaultTableModel) TablePorteur.getModel();
        
      // Parcour la collection de porteurs présente dans le bouchon et créé pour chaque porteur une ligne dans le tableau avec ses informations.
        for (Porteur p : lesPorteurs) {
            
        tm1.addRow(new Object[]{p.getLicence(), p.getNom_por(),p.getPre_por(), p.getClub_mandate(),link_main.getNBvoix(p)});
            
        }
        
        
        
    }

    private ListePorteur() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablePorteur = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Liste des porteurs");

        TablePorteur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Licence", "Nom", "Prénom", "Club mandateur", "Nombre de voix attribué"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablePorteur);

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * 
     * @param evt correspond à un clic sur le bouton retour
     * Affiche la vue Accueil et ferme la vue ListePorteur.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Accueil acc = new Accueil(link_main);
        acc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablePorteur;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
