--AGU 25-09-2019 CREATION
--JVA-01 07-10-2019 MODIFICATION
--
CREATE TABLE CLUB (
cod_clu CHAR(6),
nom_clu VARCHAR(150),
nbr_voi INTEGER,
por_clu CHAR(6),
CONSTRAINT PK_CLUB PRIMARY KEY (cod_clu));
--
CREATE TABLE PORTEUR (
num_por CHAR(6),
nom_por VARCHAR(50),
pre_por VARCHAR(50),
clu_mandat CHAR(6),
CONSTRAINT PK_PORTEUR PRIMARY KEY (num_por));
--
--creation des clef etrangeres
ALTER TABLE CLUB ADD CONSTRAINT FK_CLUB_PORTEUR FOREIGN KEY (por_clu) REFERENCES PORTEUR(num_por);
ALTER TABLE PORTEUR ADD CONSTRAINT FK_MANDATAIRE FOREIGN KEY (clu_mandat) REFERENCES CLUB(cod_clu);